// AUTO-GENERATED by scripts/export-hermes-themes.py. Do not edit by hand.
// Canonical source: ../hermes_cli/skin_engine.py::_BUILTIN_SKINS

export const HERMES_CLI_THEMES = [
  {
    "name": "default",
    "label": "Classic Hermes",
    "description": "Classic Hermes \u2014 gold and kawaii",
    "swatches": [
      "#FFF8DC",
      "#1a1a2e",
      "#ffbd38"
    ],
    "palette": {
      "background": {
        "hex": "#041c1c",
        "alpha": 1
      },
      "midground": {
        "hex": "#FFF8DC",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#ffbd38",
      "warmGlowDeep": "#d49a2e",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-1.png",
      "position": "center 18%",
      "size": "cover",
      "opacity": 0.22,
      "filter": "saturate(0.9) hue-rotate(6deg) contrast(1.02)"
    }
  },
  {
    "name": "ares",
    "label": "War-god",
    "description": "War-god theme \u2014 crimson and bronze",
    "swatches": [
      "#F1E6CF",
      "#2A1212",
      "#DD4A3A"
    ],
    "palette": {
      "background": {
        "hex": "#2A1212",
        "alpha": 1
      },
      "midground": {
        "hex": "#F1E6CF",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#DD4A3A",
      "warmGlowDeep": "#C7A96B",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-3.png",
      "position": "center 16%",
      "size": "cover",
      "opacity": 0.18,
      "filter": "sepia(0.85) hue-rotate(318deg) saturate(1.65) contrast(1.05)"
    }
  },
  {
    "name": "mono",
    "label": "Monochrome",
    "description": "Monochrome \u2014 clean grayscale",
    "swatches": [
      "#c9d1d9",
      "#1F1F1F",
      "#aaaaaa"
    ],
    "palette": {
      "background": {
        "hex": "#1F1F1F",
        "alpha": 1
      },
      "midground": {
        "hex": "#c9d1d9",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#aaaaaa",
      "warmGlowDeep": "#888888",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-2.png",
      "position": "center 14%",
      "size": "cover",
      "opacity": 0.12,
      "filter": "grayscale(1) contrast(1.12) brightness(0.8)"
    }
  },
  {
    "name": "slate",
    "label": "Cool blue",
    "description": "Cool blue \u2014 developer-focused",
    "swatches": [
      "#c9d1d9",
      "#151C2F",
      "#7eb8f6"
    ],
    "palette": {
      "background": {
        "hex": "#151C2F",
        "alpha": 1
      },
      "midground": {
        "hex": "#c9d1d9",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#7eb8f6",
      "warmGlowDeep": "#8EA8FF",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-2.png",
      "position": "center 14%",
      "size": "cover",
      "opacity": 0.18,
      "filter": "saturate(0.9) hue-rotate(20deg) contrast(1.05)"
    }
  },
  {
    "name": "daylight",
    "label": "Light terminal",
    "description": "Light theme for bright terminals with dark text and cool blue accents",
    "swatches": [
      "#111827",
      "#E5EDF8",
      "#2563EB"
    ],
    "palette": {
      "background": {
        "hex": "#E5EDF8",
        "alpha": 1
      },
      "midground": {
        "hex": "#111827",
        "alpha": 1
      },
      "foreground": {
        "hex": "#000000",
        "alpha": 0
      },
      "warmGlow": "#2563EB",
      "warmGlowDeep": "#0F766E",
      "noiseOpacity": 0.3
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-1.png",
      "position": "center center",
      "size": "cover",
      "opacity": 0.0,
      "filter": "none"
    }
  },
  {
    "name": "warm-lightmode",
    "label": "Warm light mode",
    "description": "Warm light mode \u2014 dark brown/gold text for light terminal backgrounds",
    "swatches": [
      "#2C1810",
      "#F5F0E8",
      "#8B4513"
    ],
    "palette": {
      "background": {
        "hex": "#F5F0E8",
        "alpha": 1
      },
      "midground": {
        "hex": "#2C1810",
        "alpha": 1
      },
      "foreground": {
        "hex": "#000000",
        "alpha": 0
      },
      "warmGlow": "#8B4513",
      "warmGlowDeep": "#5C3D11",
      "noiseOpacity": 0.3
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-1.png",
      "position": "center center",
      "size": "cover",
      "opacity": 0.0,
      "filter": "none"
    }
  },
  {
    "name": "poseidon",
    "label": "Ocean-god",
    "description": "Ocean-god theme \u2014 deep blue and seafoam",
    "swatches": [
      "#EAF7FF",
      "#0F2440",
      "#5DB8F5"
    ],
    "palette": {
      "background": {
        "hex": "#0F2440",
        "alpha": 1
      },
      "midground": {
        "hex": "#EAF7FF",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#5DB8F5",
      "warmGlowDeep": "#A9DFFF",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-4.png",
      "position": "center 14%",
      "size": "cover",
      "opacity": 0.16,
      "filter": "saturate(1.05) hue-rotate(115deg) contrast(1.05)"
    }
  },
  {
    "name": "sisyphus",
    "label": "Sisyphean",
    "description": "Sisyphean theme \u2014 austere grayscale with persistence",
    "swatches": [
      "#F5F5F5",
      "#202020",
      "#E7E7E7"
    ],
    "palette": {
      "background": {
        "hex": "#202020",
        "alpha": 1
      },
      "midground": {
        "hex": "#F5F5F5",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#E7E7E7",
      "warmGlowDeep": "#D3D3D3",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-2.png",
      "position": "center 14%",
      "size": "cover",
      "opacity": 0.1,
      "filter": "grayscale(1) contrast(1.1) brightness(0.75)"
    }
  },
  {
    "name": "charizard",
    "label": "Volcanic",
    "description": "Volcanic theme \u2014 burnt orange and ember",
    "swatches": [
      "#FFF0D4",
      "#2B160E",
      "#F29C38"
    ],
    "palette": {
      "background": {
        "hex": "#2B160E",
        "alpha": 1
      },
      "midground": {
        "hex": "#FFF0D4",
        "alpha": 1
      },
      "foreground": {
        "hex": "#ffffff",
        "alpha": 0
      },
      "warmGlow": "#F29C38",
      "warmGlowDeep": "#FFD39A",
      "noiseOpacity": 1
    },
    "backgroundArt": {
      "image": "/theme-backgrounds/theme-3.png",
      "position": "center 16%",
      "size": "cover",
      "opacity": 0.2,
      "filter": "sepia(0.75) hue-rotate(345deg) saturate(1.7) contrast(1.08)"
    }
  }
] as const;
