import type { BootstrapResponse, ConversationMessage } from "@/lib/types";

const now = "2026-04-21T19:30:00.000Z";

export const mockBootstrap: BootstrapResponse = {
  generated_at: now,
  summary: {
    agent_count: 1,
    conversation_count: 1,
    active_agents: 1,
    total_input_tokens: 12840,
    total_output_tokens: 9640,
    total_tokens: 22480,
    total_estimated_cost: 18.42,
    total_actual_cost: 17.96,
    daily_spend: 3.14,
    monthly_spend: 17.96,
    alerting_agents: 0,
  },
  catalog: {
    models: ["gpt-5.4", "claude-sonnet-4", "qwen/qwen3-8b"],
    toolsets: [
      { name: "terminal", description: "Local shell execution and process control", tool_count: 4 },
      { name: "file", description: "Read, write, search, and patch project files", tool_count: 5 },
      { name: "web", description: "Search and extract web content", tool_count: 2 },
    ],
    status_options: ["active", "paused", "archived"],
    entity_options: ["Umbrella Holdings Group, LLC"],
    function_options: ["Operations", "Growth", "R&D"],
  },
  entities: [
    { id: "ent_demo_trust", name: "Umbrella Corporation Trust", type: "trust", parent_id: null, display_order: 0, description: "", messaging_policy: "open", metadata: { ein: null, state: null, formation_date: null }, created_at: now, updated_at: now },
    { id: "ent_demo_holdings", name: "Umbrella Holdings Group, LLC", type: "llc", parent_id: "ent_demo_trust", display_order: 0, description: "", messaging_policy: "open", metadata: { ein: null, state: null, formation_date: null }, created_at: now, updated_at: now },
  ],
  entity_tree: [
    { id: "ent_demo_trust", name: "Umbrella Corporation Trust", type: "trust", parent_id: null, display_order: 0, description: "", messaging_policy: "open", metadata: { ein: null, state: null, formation_date: null }, created_at: now, updated_at: now, agents: [], children: [
      { id: "ent_demo_holdings", name: "Umbrella Holdings Group, LLC", type: "llc", parent_id: "ent_demo_trust", display_order: 0, description: "", messaging_policy: "open", metadata: { ein: null, state: null, formation_date: null }, created_at: now, updated_at: now, agents: [], children: [] },
    ] },
  ],
  agents: [
    {
      id: "agent_demo_ops",
      name: "Mission Control Operator",
      role: "Keep the control plane available, monitored, and ready for recovery.",
      business_function: "Operations",
      operating_entity: "Umbrella Holdings Group, LLC",
      entity_id: "ent_demo_holdings",
      description: "Preview operator for Mission Control.",
      display_order: 0,
      is_briefing_agent: false,
      deleted_at: null,
      purge_at: null,
      deleted_by: null,
      team_grouping: "Platform",
      system_prompt: "You manage the Mission Control operating surface and maintain availability.",
      preferred_model: "gpt-5.4",
      fallback_model: "claude-sonnet-4",
      token_controls: {
        max_input_tokens: 64000,
        max_output_tokens: 8000,
        max_total_tokens: 72000,
        max_context_messages: 40,
      },
      budget_controls: {
        daily_usd: 25,
        monthly_usd: 500,
        alert_threshold_pct: 80,
        hard_stop: false,
      },
      tool_permissions: {
        enabled: ["terminal", "file", "web"],
      },
      memory: {
        enabled: true,
        injection_limit: 8,
        records: [
          {
            id: "mem_demo_status",
            title: "Availability default",
            category: "operations",
            content: "If the live Mission Control API is unavailable, keep the standalone UI usable with preview data instead of failing closed.",
            active: true,
            updated_at: now,
          },
        ],
      },
      observability: {
        logging_level: "info",
        store_transcripts: true,
        status: "active",
        last_error: "",
      },
      advanced: {
        reasoning_effort: "medium",
        temperature: 0.2,
        notes: "Offline preview data is active until the live API is connected.",
        metadata: {
          source: "mock-preview",
        },
      },
      pinned: true,
      created_at: now,
      updated_at: now,
      last_active_at: now,
      usage_summary: {
        conversation_count: 1,
        input_tokens: 12840,
        output_tokens: 9640,
        total_tokens: 22480,
        estimated_cost: 18.42,
        actual_cost: 17.96,
        daily_spend: 3.14,
        monthly_spend: 17.96,
        last_run_status: "success",
        message_count: 8,
        tool_call_count: 5,
        model: "gpt-5.4",
      },
      usage_diagnostics: {
        connection_state: "unknown",
        metrics_state: "partial",
        raw_usage_found: false,
        route_label: "Standalone preview",
        provider_label: "Mission Control preview mode",
        api_mode: "offline-preview",
        base_url: "http://localhost:9120",
        status_label: "Preview data active",
        detail: "The standalone UI loaded with local preview data because the live Mission Control API was unavailable.",
        command_hint: "Start the backing API when ready; the UI will use it automatically on the next refresh.",
      },
      provider_capabilities: {
        active_provider_label: "Preview mode",
        route_type_label: "Standalone UI",
        connection_label: "Local fallback",
        usage_support: "unknown",
        cost_support: "unknown",
        cache_support: "unknown",
        limit_support: "unknown",
        detail: "The page is operational with local seed data so the interface always loads.",
        requested_model: "gpt-5.4",
        effective_model: "gpt-5.4",
        effective_provider_label: "Preview mode",
        effective_route_label: "Local fallback",
        fallback_active: true,
        fallback_detail: "Swap to the live backend by exposing the Mission Control API endpoints.",
      },
      alert_summary: {
        state: "healthy",
        reasons: ["Preview mode keeps the interface available while upstream API work continues."],
      },
      recent_conversations: [],
    },
  ],
  conversations: [
    {
      id: "conv_demo_status",
      agent_id: "agent_demo_ops",
      title: "Availability recovery plan",
      session_id: "preview-session",
      pinned: true,
      created_at: now,
      updated_at: now,
      last_message_at: now,
      last_run_status: "success",
      last_error: "",
      usage_summary: {
        conversation_count: 1,
        input_tokens: 4200,
        output_tokens: 3100,
        total_tokens: 7300,
        estimated_cost: 6.12,
        actual_cost: 5.98,
        daily_spend: 1.04,
        monthly_spend: 5.98,
        last_run_status: "success",
        message_count: 4,
        tool_call_count: 2,
        model: "gpt-5.4",
      },
      usage_diagnostics: {
        connection_state: "unknown",
        metrics_state: "partial",
        raw_usage_found: false,
        route_label: "Standalone preview",
        provider_label: "Mission Control preview mode",
        status_label: "Preview transcript",
        detail: "This conversation is local seed data used to keep the UI functional when the API is unavailable.",
      },
      provider_capabilities: {
        active_provider_label: "Preview mode",
        route_type_label: "Standalone UI",
        connection_label: "Local fallback",
        usage_support: "unknown",
        cost_support: "unknown",
        cache_support: "unknown",
        limit_support: "unknown",
        detail: "Preview conversations are read-only examples until the live API is connected.",
        requested_model: "gpt-5.4",
        effective_model: "gpt-5.4",
        effective_provider_label: "Preview mode",
        effective_route_label: "Local fallback",
        fallback_active: true,
        fallback_detail: "Connect the live API to replace seed data with real conversations.",
      },
    },
  ],
  audit_log: [
    {
      id: "audit_preview_bootstrap",
      event: "preview_bootstrap_loaded",
      detail: {
        source: "local-mock",
        note: "Fallback data rendered because the live API did not answer with Mission Control JSON.",
      },
      created_at: now,
    },
  ],
};

export const mockConversationMessages: Record<string, ConversationMessage[]> = {
  conv_demo_status: [
    {
      id: 1,
      role: "system",
      content: "Preview transcript loaded from local fallback data.",
      timestamp: 1713727800000,
      finish_reason: "stop",
    },
    {
      id: 2,
      role: "user",
      content: "Why did Mission Control fail to load?",
      timestamp: 1713727860000,
      finish_reason: "stop",
    },
    {
      id: 3,
      role: "assistant",
      content: "The standalone app had no running Vite server, the dependency install was missing, and its /api proxy pointed back to port 9120 instead of a backend. Preview mode now prevents a blank failure state when the API is unavailable.",
      timestamp: 1713727920000,
      finish_reason: "stop",
    },
  ],
};
